### PR TITLE
New add folder model refresh on items count changed

### PR DESCRIPTION
**Pull request by nfsprodriver**
-Replaced separate File / Folder add dialog by one
-Tell app to refresh model when the item count changed (file added,
deleted, pasted) so "Empty Dir" state is directly updated.

### CODE REVIEW

**Comment by sverzegnassi** [comment]
Need some context for commit 265f29813fc8681ac8313f6cbafa6be68c688910
I see you added some code to trigger a refresh of FolderListModel. For what I see in the source code of the component, this is already triggered by default any time a file is added or removed, and seems to work.
Did you find some case where this wasn't working? If so, it's preferable to patch the C++ component directly. :)

**Comment by nfsprodriver** [comment]
When I add an item to an empty folder the "Empty folder" hint doesn't disappear from itself. Refreshing solves this, but I bet there could be a better solution.

**Comment by sverzegnassi** [comment]
I don't really want to know how many bugs still exist in that plugin, anyway the issue has been fixed with dc4e15f918e338c58a6a758f5cb577bf2acf3ee7 - Well spotted!

The rest of your PR looks good to me, we can merge it once the refresh() code is removed.
After that, there's not much left to do. I would stop for a moment for discussing how to deal with that ContentHub thing and see if we can find a more natural way to open or manage file content through delegates.

**Comment by nfsprodriver** [comment]
Very cool! Do you want to remove it or should I?

**Comment by sverzegnassi** [comment]
As you prefer! If you wish or want to do it now, go for it, otherwise I'll do it tomorrow morning :)

**Pull request merged**
